hostname: &hostname grafana.yas.local.com
prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
grafana:
  grafana.ini: {}
  adminUser: admin
  adminPassword: admin
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - *hostname
